#!/bin/bash
#writen by dberistain

#Defining some colors =========================
red="$(tput setaf 196)";
yellow="$(tput setaf 226)";
blue="$(tput setaf 69)";
green="$(tput setaf 118)";
gray="$(tput setaf 237)";
bold="$(tput bold)";
r="$(tput sgr0)";
blink="$(tput blink)";
#Defining some colors [END] ===================


#Defining bar spacers parameters ==============
masterWidth="148";
bbar=$(printf '%0.s—' $(seq 1 $masterWidth)) ;
pbbar=$(printf '%0.s_' $(seq 1 $masterWidth)) ;
flag=$1
#Defining bar spacers parameters [END] ========


center() {
  width=$masterWidth
  echo;echo "$blue$bbar$r"
  for i
  do
    iCount="${#i}"
    if [ $(($iCount%2)) -eq 0 ];then fill="";else fill=" ";fi
    padding=$(( ( $width - $iCount - 2) / 2 ))
    padding=$(printf '%0.s ' $(seq 1 $padding))
    echo "$padding" "$bold$i$r" "$padding""$fill"
  done
  echo "$blue$bbar$r"
}

depCheck() {
    dependencies_missing_count=0

    for dependency in "$@"; do
        if ! command -v "$dependency" &>/dev/null; then
            echo "$dependency is not installed."
            dependencies_missing_count=$((dependencies_missing_count + 1))
        fi
    done

    if [ "$dependencies_missing_count" -eq 0 ]; then
        echo "All required packages are installed. Continuing to execute the script."
    else
        echo "There are $dependencies_missing_count missing packages for this command to run properly."
        echo "Attempting to run the script, but it may not work properly."
    fi
}

depCheck "$@"